<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="net.wukl.cacofony.exception.DefaultExceptionHandlerTest" tests="4" skipped="0" failures="0" errors="0" timestamp="2019-01-21T16:13:41" hostname="versenwald" time="0.004">
  <properties/>
  <testcase name="testGenericExceptionWithMessage()" classname="net.wukl.cacofony.exception.DefaultExceptionHandlerTest" time="0.001"/>
  <testcase name="testHttpExceptionWithMessage()" classname="net.wukl.cacofony.exception.DefaultExceptionHandlerTest" time="0.001"/>
  <testcase name="testGenericExceptionWithoutMessage()" classname="net.wukl.cacofony.exception.DefaultExceptionHandlerTest" time="0.0"/>
  <testcase name="testHttpExceptionWithoutMessage()" classname="net.wukl.cacofony.exception.DefaultExceptionHandlerTest" time="0.0"/>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
